version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
      - "27017:27017"
    network_mode: "host"
    environment:
         MONGO_INITDB_ROOT_USERNAME: test
         MONGO_INITDB_ROOT_PASSWORD: test
         MONGO_INITDB_DATABASE: Articles
  article_api:
    image: iamyogeshg/article-api #change image name in case you are building locally
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    network_mode: "host"
    environment:
         PORT: 8000
